// <auto-generated />
using System;
using BeringungApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeringungApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526144706_AddRingnummerTypToArtenInfos")]
    partial class AddRingnummerTypToArtenInfos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BeringungApi.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveStandortId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveStandortId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("BeringungApi.Models.ArtenInfos", b =>
                {
                    b.Property<string>("Artbezeichnung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxFluegellaenge")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxGewicht")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinFluegellaenge")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinGewicht")
                        .HasColumnType("REAL");

                    b.Property<string>("RingnummerTyp")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Artbezeichnung");

                    b.ToTable("ArtenInfos");
                });

            modelBuilder.Entity("BeringungApi.Models.StandortDaten", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Koordinaten")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Standort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StandortDaten");
                });

            modelBuilder.Entity("BeringungApi.Models.VogelErfassung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Alter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bemerkungen")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Beringungsdatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beringungsort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Fluegellaenge")
                        .HasColumnType("REAL");

                    b.Property<int>("Geschlecht")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gewicht")
                        .HasColumnType("REAL");

                    b.Property<string>("Koordinaten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ringnummer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vogelart")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Wiederfang")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VogelErfassungen");
                });

            modelBuilder.Entity("BeringungApi.Models.AppSettings", b =>
                {
                    b.HasOne("BeringungApi.Models.StandortDaten", "ActiveStandort")
                        .WithMany()
                        .HasForeignKey("ActiveStandortId");

                    b.Navigation("ActiveStandort");
                });
#pragma warning restore 612, 618
        }
    }
}
